<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-android</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia.Android" Version="11.3.13" />
      <PackageReference Include="Xamarin.Google.Android.Material" Version="1.13.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Jc.PopupView.Avalonia.Native\Jc.PopupView.Avalonia.Native.csproj" />
    </ItemGroup>

</Project>
