name: Build

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: 9.0.x

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore workloads
        run: dotnet workload restore
      - name: Restore dependencies
        run: dotnet restore jc-popupview-avalonia.sln
      - name: Build
        run: dotnet build jc-popupview-avalonia.sln --no-restore